server:
  port: 9003

spring:
  application:
    name: springcloud-comsumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/

#启用hystrix
feign:
  hystrix:
    enabled: true

#hystrix超时时间配置 （如果不配置的话默认是1000毫秒超时）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000